version: '3.8'

services:
  backend:
    build:
      context: .
      target: backend-builder
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - backend_uploads:/app/backend/uploads
    environment:
      - NODE_ENV=development
      - PORT=8000
    command: pnpm dev
    depends_on:
      - db

  frontend:
    build:
      context: .
      target: frontend-builder  
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8000
    command: pnpm dev
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: exam_proctor
      POSTGRES_USER: proctor
      POSTGRES_PASSWORD: secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  backend_uploads:
